import { jsonLinkingData } from "@constants/linkingData";
import { Html, Head, Main, NextScript } from "next/document";
import Script from "next/script";

const Document = () => {
  const jsonLd = {
    "@context": "http://schema.org",
    "@type": "NewsArticle",
    jsonLinkingData,
  };
  return (
    <Html lang="en" prefix="og: https://ogp.me/ns#">
      <Head>
        <meta property="og:title" content="Dealer Marketing" />
        <meta name="description" content="Generated by create next app" />
        <meta
          property="og:url"
          content="https://dealer-marketing.vercel.app/"
        />
        <meta
          property="og:image"
          content="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQsAAAC9CAMAAACTb6i8AAAAtFBMVEX////urx8AAADtqQDurhfurQ7tqwD0y4DwvFD32aXtqAD0zoiOjo7t7e3KyspycnL29va9vb1QUFCYmJiFhYViYmLY2NjQ0NDwuURmZmY5OTlJSUm4uLjFxcXg4OCnp6d5eXlDQ0Pn5+f66Mienp4oKCj43rDvtTcwMDD779kUFBQdHR321Zv++e/99eX77tfzyHbxv1v5473wukvywmb33KxZWVkXFxf10pPzyHj0zITvsy3YSyDtAAALlUlEQVR4nO2b6VrqOhSGazoo2NJSoJWpLSKDyiQbObq9//s6mZsOIGwE9nnOen9oh4DN58oaklTTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOBvZTn+WL09YN5WH+Pnaz/N9Vh+POi6ZZoGxTQtXb+bLa79VFdgPrvRTeMmh2HpX5X5tZ/tsiw2JUJIOW7/R2rMV1WzXAiGqf++9iNeioq+VwmqhjW+9lNegvmDnum0Tv0n/mVZ6qjR3679oOdnqKc9NnVrUxnyyLEYzjaWYjGmubzuk56djyo2AoZl3Bd6O/y0LKlG9X8xTvZRMaQa1dm1H+bqzORI0UGM+Ztwr9X3az/Ln7B8uDuNVUXxHpWqEGNY8rdeOwS/WTvqCWsIuaf18WCqxmngsGqtZM+XItzoJTkoEvzTP+IBL6jF7zQA/DGmPhFqLHiObkyKfwqlHNG7C2qhTb7NJg/A0N+4ISy4ttZH4S9hDfBPrz7FB+2Dn++SWmhv+o5y6yhMfc2+7pk70GqhjMcSePTAxkdPhz7eRbXQ1pOd1ecxiLRizcQwfuX/jtSCiuHI646Tb6mS0WJ/0x/h+eMXrSwOYqcY+j37tk826vR8LEm10DoINXlXt8R/tAPZKkpeEHpJIq2JUF1TtQhbatPu6CUM2yP0eAY9Fsv1uHIA7xPWc4MKgxVMTUrkWDf0UsF9KlrUmO/QtJbwplwaogDDzmvRFncSeorl7JKzc2hxMA+0pyYzgvmy8pD6G55WDPVSw1C0IMeRRjuERq6LpDelVtLp8F6rWpCOv7ouNhq01fhHyaXzj5o9ZLQgLO9kOW+xaHLHDCNXv6tatGhHiRHQXCPGBzH+/SS8ai+vhc1P6R3SlGjxelzadgTPn7cH8PvrJqeFpo2FGOaGni+5YWQTLlWLhHTI4daB6dNB4+GfvHtOVgtyhzsKPr46YpidhUXVPISbohbas/AaVZaR/6KnViXz/aoWeFj0iBU0lAt9Yh6JuBBktMB3bHEnIZ8lWsQ/rYDC3RFpV1YLmWLxSLq2SsKqqsWUGAAeKH6L0yWddeU/HzNQtXCVpj71tB0+vM7E/IisK6eFNuRlmc5WjqySQaJo4dDjAcrgEs8p1crGVD/btH12LbSFcXB1ktdCu2VGZX7Ssw09szKRRNEC97NLO9hspNSJoaRhwVW1aGWb9s6vhabd69ZhtlHQQhOFCD0Z0zMzU5SkWgQsfjTpwFew1QsZf2EXvMP5tcC92OAq3DrSdxI+1HRzQSNJNqpKLR4RNQstxAmmuNntTgOi0au4YGe0CJSo4Q+m4WW00Mjc9nh2f0xMpcxZIDVZ8smtRG0gukOSCaYK7o/P7mFPMdBoQrVlF+xcfuGzBhodLlPtYlrsp5BrZW8YG+VEV++TTLvZZFk3y5yJgaBGv087TjwFzSoatdrTaz7Xonfsfr8hmv7dWtzTQWJ80RPmPDOBJA0DvvChQXqNJV2RPH/ZZnPw9A6Lu5fUYr0jC905RnhSwZ3nb1OJsAwZEMP0mueya4mXu+DylIpkpO3sHdZ0dEktdmWhu3ynLMnoyUdRi4CSryu9fhz3vZILnuOQy14QRGVN8Vd52qUw9gbXEi0yVUiJFv9hltUjtRha++3iv8xw3yaDEi3eVS1YGqqrk569widwfD3pCYN6jw25qF8/84CZr6o7s9ASLXgWznKKjZGOF05zUPhIo3PSA8o8taEWdWdiXrkrZKE7tWA3eK45KeYXtkisJHHhynE0+PzORbQgLNbvH/cHxFTuOnkNwnLwL7WBLZNKTh39lBZR/cxjZMdWtF251katR9gqCc9BOSS7VMUI0Y9pcXZW5ZtKdmgh1ojYsKiwOjWz+YBm2qkYNOc8WYsL5VvjqnG7LhrHDi2YgxAznm9GaiMCqgVq8bNHpGoRNv2ui/3gk9smxv6UJI8O/sFuRknCl9ni7euozdxlkDSbuGBrNZu4VS2OcUCpJ0mo9ZNtq6laixc3kwb2Jg3XjbQ/BdfdpqXfbHKXy7W45YUp6/5cTUGzWvCM2kGKFo6Y4aq7rPDCtQjJuHlF/8KneHqiVCF9qqf1CZ0JqVEzicU3yQDOF1wGThuhUPtjvkr+uTu0+OAjhHtLlmrkFgWwFr4QwyPrHAnX4jHt1ivrNl9CYpMZvDChCwbIH/DqrFyLFG5JHXmhc5IWLHfML3OUaXErFgX4CjNTMbfbE2uRhFwMXFmhOORaYF26ATFm+sxCixF3BTU+roh/IamZh7Uh0x+ex/IL/FvVwg89L/RFNUu+6ClyAmYdJ2ix4JaeTaSLWjw/iGlSPvM9LBsi5MnbzM4Tsghmk2OixZN0Io6ihZjg8hCfAurIoNEUCwQyjqRa8LVIl311iMQManSiFnyZI2cYeS2Wm3T6nOfczI+aqxItpG0nmtDiNZ2+C1MtxIDf8i48Kps2/uGfKGohpwiZgu000PRO1GJdtjAqpq/WY8xsZShVi84GxbjUnrgWtL/siGnhqZsKplKLUHahKQ46XYY/4v/tohZy7WlLBwlS1tZO1IKPeyMzbfnAdyHRdXZTLd/0W9pgzkaMcZf7Mq4FNdetJrWIlB5ortSiJnvADmKUISjXoqd8UY18Oq2BBidqwQ2DL3pktChi8ej7xvSp5ut1oQU2966WauGkGw7oFG9Wi4ZYDCAG0q8Let73WoRECzloyMA6SQvRcbEBaZ8WOncPM65fPi9JtdD4ghD3F8rKgIfyWhCXSevyqGST17daDNLFp+jUMaI9Z5cGCeVaGFW+kLwWnyhkrHa+N1wLOx0k3aIW2GxG9GAk+1JnqwIHaBGnmW3nZC20e7EcJmdlSrXQJ1ysoShLilt/d2nhIR4jow4qaiG9Z01kk8RzRIdpQdxNl7StjU6NqYSJcJXCMopa4FAiei6kMEveI9mlBYssLXeKUJkWMqrSHL5Fd+7w6bDvtWArCSPucE/VYi5TymGJFnTj7530Ju9Vcbnkm+y0MJNaMCcaiujQKMQRAuLLbE+imSi9vo0jyrIKKeRO1ULuJripslmaibKnz/x6u1dK2U+pW9k7mrG/tTMX+v42kffwf6/5iAtUuvzR3PrKPFXN95lDcWxsO4MnOW0Td7tMsri1DciX+LKEb8hviLETenED4otO1gLX7ryH1sPe11CXXyLZKN0af22mPzIPKLf/G9XdbxrOV1UxeKrrna0uTeQKW3DQz+zvepdLJaZ+Xzr1t/hMU/HCJtfrEYjoS0uT1t62h7JOyy9Tvxvn5Fi8P6RKGNbf9PJdl8zikANXBuKTWdykhQd5Y/vzffi8mM8Xz8PK6kbdy2NNzvD28iNznR5xvWx1KMKjf0rNP3ZY7fsPqjUSjzZEQSCiDZ0F2DbbSiD+AVbqxjYcSckbquQlVUutzoxqcdnkB3BYP6YJ+UESrwjZjtOgqfsrFsiLHp12V7NdjU5nES34yrSyq+End0AOb77d2KZPzjM+HNqTAck/gxHxgANZzYVT5hEjnJcQLUg6T7SQn+VbFdwf3jc+2/OSABk65rleuXNQA8XbEZnxbvXcmPQWX6SbEfw+mxcfYfMgWoQ4nc9ogYnCH/IUGWbmri2gpn5zvpcPHURyVA1r4SFsAVgLUne94qwV3wnIUIlJ54kW3iPWDWvhtpOzPY5g/aZb+TdvDFPXN+cMpA4eAHWHaGG/2jZOrtt0Lmj0pDVH+DzEEhE/SrRwyIDCWtT6F1lFWn9+0Rf72Svd2IdOfp85o3DYLESSYN8Yx8kA993v16e4lkdxHLs+rl96cRzZrkcaOigkWtQv9GbJfDme3X+uVp/3s/UF0glvS2NCHAcJ+Y3PvOZoir1kjfhQrxW13Xa71e/FGl11c4Ko3W5vT68+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAP+BeKjtRpy1O/EAAAAABJRU5ErkJggg=="
        />
        <link rel="icon" href="/favicon.ico" />
        <Script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        {/* Google Tag Manager */}
        <Script
          strategy="afterInteractive"
          type="text/partytown"
          dangerouslySetInnerHTML={{
            __html: `(function (w, d, s, l, i) {
            w[l] = w[l] || [];
            w[l].push({ "gtm.start": new Date().getTime(), event: "gtm.js" });
            var f = d.getElementsByTagName(s)[0],
              j = d.createElement(s),
              dl = l != "dataLayer" ? "&l=" + l : "";
            j.async = true;
            j.src = "https://www.googletagmanager.com/gtm.js?id=" + i + dl;
            f.parentNode.insertBefore(j, f);
          })(window, document, "script", "dataLayer", "GTM-WK9ZN93")`,
          }}></Script>
        {/* End Google Tag Manager */}
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
};

export default Document;
